# Global config
global:
  scrape_interval: 10s
  evaluation_interval: 10s

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spark-antifraud'
    static_configs:
      - targets: ['host.docker.internal:9091']
    metrics_path: '/metrics'